theme: jekyll-theme-minimal
left-title: åŸºæœ¬ä¿¡æ¯
base-info: ğŸ‰ï¼šé»„æ·»è±ª ç”· 1999-11 24å²
phone: ğŸ“±ï¼š15577400013
email: ğŸ“§ï¼š920240746@qq.com
educational-background: ğŸ«ï¼šå¹¿è¥¿å¤–å›½è¯­å­¦é™¢ è½¯ä»¶å·¥ç¨‹ 2023å±Š
weixin: å¾®ä¿¡ï¼šXytQAZ123_